# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 100.69.158.196/backend
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeport: 1337

configuration:
  pod_directory: /usr/share/nginx/html/conf
  files:
    vertcoin.conf: |
      abc=xyz
      #a=1
      b=2
    second.conf: |
      fsdf'sd
      Fixtures.identify(:sdf'
      sdf
      'sdf
      ')


# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
#     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
#   path: /*

#   hosts:
#     - backend.faldax.com
#   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 300m
   memory: 500Mi

health:
  enable: true
  livenessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5

nodeSelector: {}

tolerations:
- key: env
  operator: Equal
  value: qa
  effect: NoSchedule
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - qa

controller:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 90 