apiVersion: v1
kind: Service
metadata:
  name: {{ include "currency.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "currency.name" . }}
    helm.sh/chart: {{ include "currency.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "currency.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
