kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "currency.name" . }}
    helm.sh/chart: {{ include "currency.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi